# Generated by Django 5.1.5 on 2025-03-19 14:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rfidticketing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="rfidcardlog",
            name="passenger_count",
            field=models.IntegerField(default=1),
        ),
    ]
