# Generated by Django 5.1.5 on 2025-03-19 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rfidticketing", "0002_rfidcardlog_passenger_count"),
    ]

    operations = [
        migrations.RenameField(
            model_name="rfidcardlog",
            old_name="timestamp",
            new_name="entry_timestamp",
        ),
        migrations.RemoveField(
            model_name="rfidcardlog",
            name="end_latitude",
        ),
        migrations.RemoveField(
            model_name="rfidcardlog",
            name="end_longitude",
        ),
        migrations.RemoveField(
            model_name="rfidcardlog",
            name="passenger_count",
        ),
        migrations.RemoveField(
            model_name="rfidcardlog",
            name="start_latitude",
        ),
        migrations.RemoveField(
            model_name="rfidcardlog",
            name="start_longitude",
        ),
        migrations.RemoveField(
            model_name="rfidcardlog",
            name="user",
        ),
        migrations.AddField(
            model_name="rfidcardlog",
            name="entry_latitude",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="rfidcardlog",
            name="entry_longitude",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="rfidcardlog",
            name="exit_latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="rfidcardlog",
            name="exit_longitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="rfidcardlog",
            name="exit_timestamp",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="rfidcardlog",
            name="fare_deducted",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="rfidcardlog",
            name="rfid_card",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="rfidticketing.rfidcard"
            ),
        ),
    ]
