# Generated by Django 5.1.5 on 2025-03-19 15:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rfidticketing", "0003_rename_timestamp_rfidcardlog_entry_timestamp_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="rfidcardlog",
            name="passenger_count",
            field=models.IntegerField(default=1),
        ),
    ]
