# Generated by Django 5.1.5 on 2025-03-20 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rfidticketing", "0004_rfidcardlog_passenger_count"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "rfid_card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rfidticketing.rfidcard",
                    ),
                ),
            ],
        ),
    ]
